name: Virtual Development Environment
on:
  workflow_dispatch:  # Dapat dijalankan manual
  schedule:
    - cron: "0 */6 * * *"  # Setiap 6 jam

jobs:
  virtual-environment:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 jam maksimal

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup tmate session (web terminal)
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true  # Hanya Anda yang bisa akses

    - name: Install basic utilities
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          curl wget git unzip \
          python3 python3-pip \
          nodejs npm \
          jq tree nano vim

    - name: Create workspace
      run: |
        mkdir -p workspace
        cd workspace
        echo "Workspace created at $(date)" > README.txt
        echo "This is a virtual environment accessible for 6 hours" >> README.txt

    - name: Start background services (contoh)
      run: |
        # Menjalankan service di background
        python3 -m http.server 8000 -d workspace > server.log 2>&1 &
        echo "Web server started on port 8000"

    - name: Upload workspace as artifact (setelah sesi selesai)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: workspace-files
        path: workspace/
        
    - name: Keep alive until timeout
      run: |
        # Script untuk menjaga environment tetap aktif
        echo "Environment akan aktif selama 6 jam"
        echo "Akses terminal melalui link yang disediakan"
        echo "File dapat diakses melalui artifacts setelah sesi berakhir"
        # Menunggu hingga timeout
        sleep 3600  # Tunggu 1 jam, lalu ulangi (akan berjalan hingga timeout 6 jam)
